/**
 * StructuralRisk report view component for MITDS
 *
 * Displays a comprehensive structural risk report with funding analysis,
 * board overlaps, infrastructure sharing, and confidence bands.
 */

import { useState, useMemo } from 'react';

// =========================
// Types
// =========================

export interface StructuralRiskData {
  metadata: {
    title: string;
    subtitle?: string;
    generated_by: string;
    generated_at: string;
    report_type: string;
  };
  executive_summary: string;
  methodology: string;
  entities_analyzed: number;
  analysis_period?: {
    start: string;
    end: string;
  };
  risk_assessment: {
    overall_score: number;
    confidence: number;
    confidence_band: {
      lower: number;
      upper: number;
    };
    category: 'high' | 'medium' | 'low' | 'minimal';
  };
  sections: StructuralRiskSection[];
  limitations: string[];
  data_sources: string[];
}

export interface StructuralRiskSection {
  id: string;
  title: string;
  content: string;
  section_type: 'funding' | 'governance' | 'infrastructure' | 'temporal' | 'summary';
  findings: StructuralRiskFinding[];
  metrics?: SectionMetrics;
}

export interface SectionMetrics {
  total_entities?: number;
  flagged_entities?: number;
  average_score?: number;
  max_score?: number;
}

export interface StructuralRiskFinding {
  id: string;
  title: string;
  description: string;
  severity: 'high' | 'medium' | 'low';
  confidence: number;
  confidence_band?: {
    lower: number;
    upper: number;
  };
  why_flagged: string;
  evidence_citations: EvidenceCitation[];
  entities_involved: EntityReference[];
  signals: SignalContribution[];
}

export interface EvidenceCitation {
  id: string;
  source_type: string;
  source_name: string;
  url?: string;
  retrieved_at: string;
  excerpt?: string;
}

export interface EntityReference {
  id: string;
  name: string;
  entity_type: string;
}

export interface SignalContribution {
  signal_type: string;
  weight: number;
  contribution: number;
  description: string;
}

interface StructuralRiskProps {
  data: StructuralRiskData;
  onEntityClick?: (entity: EntityReference) => void;
  onEvidenceClick?: (evidence: EvidenceCitation) => void;
  showConfidenceBands?: boolean;
}

// =========================
// Helper Functions
// =========================

function getSeverityColor(severity: string): string {
  switch (severity) {
    case 'high':
      return '#DC2626';
    case 'medium':
      return '#F59E0B';
    case 'low':
      return '#10B981';
    default:
      return '#6B7280';
  }
}

function getCategoryColor(category: string): string {
  switch (category) {
    case 'high':
      return '#DC2626';
    case 'medium':
      return '#F59E0B';
    case 'low':
      return '#10B981';
    case 'minimal':
      return '#6B7280';
    default:
      return '#6B7280';
  }
}

function formatConfidence(confidence: number): string {
  return `${(confidence * 100).toFixed(0)}%`;
}

function formatConfidenceBand(band: { lower: number; upper: number }): string {
  return `${(band.lower * 100).toFixed(0)}%-${(band.upper * 100).toFixed(0)}%`;
}

// =========================
// Component
// =========================

export default function StructuralRisk({
  data,
  onEntityClick,
  onEvidenceClick,
  showConfidenceBands = true,
}: StructuralRiskProps) {
  const {
    metadata,
    executive_summary,
    methodology,
    entities_analyzed,
    analysis_period,
    risk_assessment,
    sections,
    limitations,
    data_sources,
  } = data;

  // Group findings by severity for summary
  const findingSummary = useMemo(() => {
    const all = sections.flatMap((s) => s.findings);
    return {
      high: all.filter((f) => f.severity === 'high').length,
      medium: all.filter((f) => f.severity === 'medium').length,
      low: all.filter((f) => f.severity === 'low').length,
      total: all.length,
    };
  }, [sections]);

  return (
    <div className="structural-risk-report">
      {/* Report Header */}
      <header className="report-header">
        <h1>{metadata.title}</h1>
        {metadata.subtitle && <p className="subtitle">{metadata.subtitle}</p>}
        <div className="header-meta">
          <span>Generated by {metadata.generated_by}</span>
          <span>{new Date(metadata.generated_at).toLocaleString()}</span>
          {analysis_period && (
            <span>
              Analysis period: {new Date(analysis_period.start).toLocaleDateString()} -{' '}
              {new Date(analysis_period.end).toLocaleDateString()}
            </span>
          )}
        </div>
      </header>

      {/* Risk Assessment Overview */}
      <section className="risk-overview">
        <h2>Risk Assessment Overview</h2>
        <div className="overview-grid">
          <div className="overview-card main-score">
            <div className="score-display">
              <span
                className="score-value"
                style={{ color: getCategoryColor(risk_assessment.category) }}
              >
                {(risk_assessment.overall_score * 100).toFixed(0)}
              </span>
              <span className="score-label">Overall Risk Score</span>
            </div>
            <div
              className="category-badge"
              style={{ backgroundColor: getCategoryColor(risk_assessment.category) }}
            >
              {risk_assessment.category.toUpperCase()} RISK
            </div>
            {showConfidenceBands && risk_assessment.confidence_band && (
              <div className="confidence-info">
                <span>Confidence: {formatConfidence(risk_assessment.confidence)}</span>
                <span className="confidence-band">
                  Band: {formatConfidenceBand(risk_assessment.confidence_band)}
                </span>
              </div>
            )}
          </div>

          <div className="overview-card findings-summary">
            <h3>Findings Summary</h3>
            <div className="findings-bars">
              <div className="finding-bar">
                <span className="bar-label">High</span>
                <div className="bar-track">
                  <div
                    className="bar-fill"
                    style={{
                      width: `${(findingSummary.high / Math.max(findingSummary.total, 1)) * 100}%`,
                      backgroundColor: getSeverityColor('high'),
                    }}
                  />
                </div>
                <span className="bar-count">{findingSummary.high}</span>
              </div>
              <div className="finding-bar">
                <span className="bar-label">Medium</span>
                <div className="bar-track">
                  <div
                    className="bar-fill"
                    style={{
                      width: `${(findingSummary.medium / Math.max(findingSummary.total, 1)) * 100}%`,
                      backgroundColor: getSeverityColor('medium'),
                    }}
                  />
                </div>
                <span className="bar-count">{findingSummary.medium}</span>
              </div>
              <div className="finding-bar">
                <span className="bar-label">Low</span>
                <div className="bar-track">
                  <div
                    className="bar-fill"
                    style={{
                      width: `${(findingSummary.low / Math.max(findingSummary.total, 1)) * 100}%`,
                      backgroundColor: getSeverityColor('low'),
                    }}
                  />
                </div>
                <span className="bar-count">{findingSummary.low}</span>
              </div>
            </div>
            <div className="entities-count">
              {entities_analyzed} entities analyzed
            </div>
          </div>
        </div>
      </section>

      {/* Executive Summary */}
      <section className="report-section executive-summary">
        <h2>Executive Summary</h2>
        <p>{executive_summary}</p>
      </section>

      {/* Methodology */}
      <section className="report-section methodology">
        <h2>Methodology</h2>
        <p>{methodology}</p>
      </section>

      {/* Main Sections */}
      {sections.map((section) => (
        <section key={section.id} className={`report-section section-${section.section_type}`}>
          <h2>{section.title}</h2>
          <p className="section-content">{section.content}</p>

          {/* Section Metrics */}
          {section.metrics && (
            <div className="section-metrics">
              {section.metrics.total_entities !== undefined && (
                <div className="metric">
                  <span className="metric-value">{section.metrics.total_entities}</span>
                  <span className="metric-label">Entities</span>
                </div>
              )}
              {section.metrics.flagged_entities !== undefined && (
                <div className="metric">
                  <span className="metric-value">{section.metrics.flagged_entities}</span>
                  <span className="metric-label">Flagged</span>
                </div>
              )}
              {section.metrics.average_score !== undefined && (
                <div className="metric">
                  <span className="metric-value">
                    {(section.metrics.average_score * 100).toFixed(0)}%
                  </span>
                  <span className="metric-label">Avg Score</span>
                </div>
              )}
            </div>
          )}

          {/* Findings */}
          {section.findings.length > 0 && (
            <div className="findings-list">
              {section.findings.map((finding) => (
                <FindingCard
                  key={finding.id}
                  finding={finding}
                  showConfidenceBand={showConfidenceBands}
                  onEntityClick={onEntityClick}
                  onEvidenceClick={onEvidenceClick}
                />
              ))}
            </div>
          )}
        </section>
      ))}

      {/* Data Sources */}
      {data_sources.length > 0 && (
        <section className="report-section data-sources">
          <h2>Data Sources</h2>
          <ul>
            {data_sources.map((source, idx) => (
              <li key={idx}>{source}</li>
            ))}
          </ul>
        </section>
      )}

      {/* Limitations */}
      {limitations.length > 0 && (
        <section className="report-section limitations">
          <h2>Limitations</h2>
          <ul>
            {limitations.map((limitation, idx) => (
              <li key={idx}>{limitation}</li>
            ))}
          </ul>
        </section>
      )}

      <style>{`
        .structural-risk-report {
          max-width: 900px;
          margin: 0 auto;
          font-size: 0.9375rem;
          line-height: 1.6;
        }

        .report-header {
          margin-bottom: var(--spacing-xl);
          padding-bottom: var(--spacing-lg);
          border-bottom: 2px solid var(--border-color);
        }

        .report-header h1 {
          margin-bottom: var(--spacing-xs);
          font-size: 1.75rem;
        }

        .report-header .subtitle {
          font-size: 1.125rem;
          color: var(--text-secondary);
          margin-bottom: var(--spacing-md);
        }

        .header-meta {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-md);
          font-size: 0.875rem;
          color: var(--text-muted);
        }

        .risk-overview {
          margin-bottom: var(--spacing-xl);
        }

        .risk-overview h2 {
          margin-bottom: var(--spacing-md);
        }

        .overview-grid {
          display: grid;
          grid-template-columns: 1fr 1fr;
          gap: var(--spacing-lg);
        }

        .overview-card {
          padding: var(--spacing-lg);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
        }

        .main-score {
          display: flex;
          flex-direction: column;
          align-items: center;
          text-align: center;
        }

        .score-display {
          display: flex;
          flex-direction: column;
          margin-bottom: var(--spacing-md);
        }

        .score-value {
          font-size: 4rem;
          font-weight: 700;
          line-height: 1;
        }

        .score-label {
          font-size: 0.875rem;
          color: var(--text-muted);
          text-transform: uppercase;
          letter-spacing: 0.05em;
        }

        .category-badge {
          padding: 6px 16px;
          border-radius: 4px;
          color: white;
          font-weight: 600;
          font-size: 0.875rem;
          letter-spacing: 0.05em;
        }

        .confidence-info {
          margin-top: var(--spacing-md);
          font-size: 0.875rem;
          color: var(--text-muted);
          display: flex;
          flex-direction: column;
          gap: 2px;
        }

        .confidence-band {
          font-family: ui-monospace, monospace;
        }

        .findings-summary h3 {
          margin: 0 0 var(--spacing-md) 0;
          font-size: 1rem;
        }

        .findings-bars {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .finding-bar {
          display: grid;
          grid-template-columns: 60px 1fr 30px;
          align-items: center;
          gap: var(--spacing-sm);
        }

        .bar-label {
          font-size: 0.875rem;
          color: var(--text-secondary);
        }

        .bar-track {
          height: 8px;
          background: var(--bg-tertiary);
          border-radius: 4px;
          overflow: hidden;
        }

        .bar-fill {
          height: 100%;
          border-radius: 4px;
          transition: width 0.3s ease;
        }

        .bar-count {
          font-weight: 600;
          text-align: right;
        }

        .entities-count {
          margin-top: var(--spacing-md);
          font-size: 0.875rem;
          color: var(--text-muted);
          text-align: center;
        }

        .report-section {
          margin-bottom: var(--spacing-xl);
        }

        .report-section h2 {
          margin-bottom: var(--spacing-md);
          padding-bottom: var(--spacing-xs);
          border-bottom: 1px solid var(--border-color);
          font-size: 1.25rem;
        }

        .section-content {
          margin-bottom: var(--spacing-md);
        }

        .section-metrics {
          display: flex;
          gap: var(--spacing-lg);
          padding: var(--spacing-md);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
          margin-bottom: var(--spacing-md);
        }

        .metric {
          display: flex;
          flex-direction: column;
          align-items: center;
        }

        .metric-value {
          font-size: 1.5rem;
          font-weight: 600;
        }

        .metric-label {
          font-size: 0.75rem;
          color: var(--text-muted);
          text-transform: uppercase;
        }

        .findings-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-md);
        }

        .data-sources ul,
        .limitations ul {
          margin: 0;
          padding-left: var(--spacing-lg);
        }

        .data-sources li,
        .limitations li {
          margin-bottom: var(--spacing-xs);
          color: var(--text-secondary);
        }

        @media (max-width: 768px) {
          .overview-grid {
            grid-template-columns: 1fr;
          }

          .score-value {
            font-size: 3rem;
          }
        }
      `}</style>
    </div>
  );
}

// =========================
// Finding Card Component
// =========================

interface FindingCardProps {
  finding: StructuralRiskFinding;
  showConfidenceBand: boolean;
  onEntityClick?: (entity: EntityReference) => void;
  onEvidenceClick?: (evidence: EvidenceCitation) => void;
}

function FindingCard({
  finding,
  showConfidenceBand,
  onEntityClick,
  onEvidenceClick,
}: FindingCardProps) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div
      className="finding-card"
      style={{ borderLeftColor: getSeverityColor(finding.severity) }}
    >
      <div className="finding-header">
        <div className="finding-title-row">
          <h3>{finding.title}</h3>
          <div className="finding-badges">
            <span
              className="severity-badge"
              style={{ backgroundColor: getSeverityColor(finding.severity) }}
            >
              {finding.severity}
            </span>
            <span className="confidence-badge">
              {formatConfidence(finding.confidence)}
              {showConfidenceBand && finding.confidence_band && (
                <span className="band-text">
                  {' '}({formatConfidenceBand(finding.confidence_band)})
                </span>
              )}
            </span>
          </div>
        </div>
      </div>

      <p className="finding-description">{finding.description}</p>

      <div className="why-flagged">
        <strong>Why flagged:</strong> {finding.why_flagged}
      </div>

      {/* Signal Contributions */}
      {finding.signals.length > 0 && (
        <div className="signals-section">
          <button
            type="button"
            className="expand-btn"
            onClick={() => setExpanded(!expanded)}
          >
            {expanded ? 'Hide' : 'Show'} signal breakdown ({finding.signals.length})
          </button>
          {expanded && (
            <div className="signals-list">
              {finding.signals.map((signal, idx) => (
                <div key={idx} className="signal-item">
                  <div className="signal-header">
                    <span className="signal-type">{signal.signal_type}</span>
                    <span className="signal-contribution">
                      +{(signal.contribution * 100).toFixed(1)}%
                    </span>
                  </div>
                  <div className="signal-bar">
                    <div
                      className="signal-bar-fill"
                      style={{ width: `${signal.contribution * 100}%` }}
                    />
                  </div>
                  <p className="signal-description">{signal.description}</p>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {/* Entities Involved */}
      {finding.entities_involved.length > 0 && (
        <div className="entities-section">
          <span className="section-label">Entities involved:</span>
          <div className="entity-chips">
            {finding.entities_involved.map((entity) => (
              <button
                key={entity.id}
                type="button"
                className="entity-chip"
                onClick={() => onEntityClick?.(entity)}
              >
                {entity.name}
                <span className="entity-type">{entity.entity_type}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Evidence Citations */}
      {finding.evidence_citations.length > 0 && (
        <div className="evidence-section">
          <span className="section-label">Evidence:</span>
          <div className="evidence-list">
            {finding.evidence_citations.map((evidence) => (
              <button
                key={evidence.id}
                type="button"
                className="evidence-item"
                onClick={() => onEvidenceClick?.(evidence)}
              >
                <span className="evidence-source">{evidence.source_name}</span>
                <span className="evidence-type">{evidence.source_type}</span>
              </button>
            ))}
          </div>
        </div>
      )}

      <style>{`
        .finding-card {
          padding: var(--spacing-md);
          background: var(--bg-primary);
          border-radius: var(--border-radius);
          border-left: 4px solid;
        }

        .finding-header {
          margin-bottom: var(--spacing-sm);
        }

        .finding-title-row {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          gap: var(--spacing-sm);
        }

        .finding-card h3 {
          margin: 0;
          font-size: 1rem;
        }

        .finding-badges {
          display: flex;
          gap: var(--spacing-xs);
          flex-shrink: 0;
        }

        .severity-badge {
          padding: 2px 8px;
          border-radius: 4px;
          color: white;
          font-size: 0.75rem;
          font-weight: 500;
          text-transform: uppercase;
        }

        .confidence-badge {
          padding: 2px 8px;
          background: var(--bg-tertiary);
          border-radius: 4px;
          font-size: 0.75rem;
        }

        .band-text {
          color: var(--text-muted);
        }

        .finding-description {
          margin-bottom: var(--spacing-sm);
        }

        .why-flagged {
          padding: var(--spacing-sm);
          background: var(--bg-tertiary);
          border-radius: var(--border-radius);
          font-size: 0.875rem;
          margin-bottom: var(--spacing-sm);
        }

        .signals-section {
          margin-top: var(--spacing-sm);
        }

        .expand-btn {
          background: none;
          border: none;
          color: var(--color-primary);
          cursor: pointer;
          font-size: 0.875rem;
          padding: 0;
        }

        .expand-btn:hover {
          text-decoration: underline;
        }

        .signals-list {
          margin-top: var(--spacing-sm);
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .signal-item {
          padding: var(--spacing-sm);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
        }

        .signal-header {
          display: flex;
          justify-content: space-between;
          margin-bottom: 4px;
        }

        .signal-type {
          font-weight: 500;
          font-size: 0.875rem;
        }

        .signal-contribution {
          font-family: ui-monospace, monospace;
          font-size: 0.875rem;
          color: var(--color-success);
        }

        .signal-bar {
          height: 4px;
          background: var(--bg-tertiary);
          border-radius: 2px;
          margin-bottom: 4px;
        }

        .signal-bar-fill {
          height: 100%;
          background: var(--color-primary);
          border-radius: 2px;
        }

        .signal-description {
          margin: 0;
          font-size: 0.75rem;
          color: var(--text-muted);
        }

        .section-label {
          font-size: 0.75rem;
          color: var(--text-muted);
          text-transform: uppercase;
          display: block;
          margin-bottom: var(--spacing-xs);
        }

        .entities-section,
        .evidence-section {
          margin-top: var(--spacing-sm);
        }

        .entity-chips {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-xs);
        }

        .entity-chip {
          display: inline-flex;
          align-items: center;
          gap: 4px;
          padding: 4px 8px;
          background: var(--bg-secondary);
          border: 1px solid var(--border-color);
          border-radius: var(--border-radius);
          cursor: pointer;
          font-size: 0.875rem;
        }

        .entity-chip:hover {
          border-color: var(--color-primary);
        }

        .entity-chip .entity-type {
          font-size: 0.625rem;
          color: var(--text-muted);
          text-transform: uppercase;
        }

        .evidence-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-xs);
        }

        .evidence-item {
          display: flex;
          justify-content: space-between;
          align-items: center;
          padding: var(--spacing-xs) var(--spacing-sm);
          background: var(--bg-secondary);
          border: 1px solid var(--border-color);
          border-radius: var(--border-radius);
          cursor: pointer;
          font-size: 0.875rem;
          text-align: left;
        }

        .evidence-item:hover {
          border-color: var(--color-primary);
        }

        .evidence-source {
          color: var(--text-primary);
        }

        .evidence-type {
          font-size: 0.75rem;
          color: var(--text-muted);
          text-transform: uppercase;
        }
      `}</style>
    </div>
  );
}

