/**
 * TopologySummary report view component for MITDS
 *
 * Displays influence topology summary with network metrics,
 * key actors, funding flows, and relationship visualizations.
 */

import { useState, useMemo } from 'react';

// =========================
// Types
// =========================

export interface TopologySummaryData {
  metadata: {
    title: string;
    subtitle?: string;
    generated_by: string;
    generated_at: string;
    report_type: string;
  };
  executive_summary: string;
  network_metrics: NetworkMetrics;
  key_actors: KeyActor[];
  funding_flows: FundingFlow[];
  relationship_clusters: RelationshipCluster[];
  temporal_changes?: TemporalChange[];
  methodology: string;
  limitations: string[];
}

export interface NetworkMetrics {
  total_nodes: number;
  total_edges: number;
  density: number;
  average_degree: number;
  clustering_coefficient: number;
  largest_component_size: number;
  diameter: number;
  centralization: number;
}

export interface KeyActor {
  id: string;
  name: string;
  entity_type: string;
  centrality_score: number;
  degree: number;
  betweenness: number;
  role_description: string;
  connected_entities: number;
}

export interface FundingFlow {
  id: string;
  source: {
    id: string;
    name: string;
    entity_type: string;
  };
  target: {
    id: string;
    name: string;
    entity_type: string;
  };
  total_amount?: number;
  currency?: string;
  period?: {
    start: string;
    end: string;
  };
  evidence_count: number;
}

export interface RelationshipCluster {
  id: string;
  name: string;
  description: string;
  member_count: number;
  internal_density: number;
  dominant_relationship_type: string;
  key_members: {
    id: string;
    name: string;
    entity_type: string;
  }[];
}

export interface TemporalChange {
  period: string;
  nodes_added: number;
  nodes_removed: number;
  edges_added: number;
  edges_removed: number;
  density_change: number;
}

interface TopologySummaryProps {
  data: TopologySummaryData;
  onEntityClick?: (entity: { id: string; name: string; entity_type: string }) => void;
  onClusterClick?: (cluster: RelationshipCluster) => void;
}

// =========================
// Helper Functions
// =========================

function formatNumber(num: number): string {
  if (num >= 1000000) return `${(num / 1000000).toFixed(1)}M`;
  if (num >= 1000) return `${(num / 1000).toFixed(1)}K`;
  return num.toString();
}

function formatCurrency(amount: number, currency: string = 'USD'): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount);
}

function formatPercent(value: number): string {
  return `${(value * 100).toFixed(1)}%`;
}

function getEntityTypeColor(type: string): string {
  const colors: Record<string, string> = {
    organization: '#3B82F6',
    person: '#8B5CF6',
    outlet: '#10B981',
    sponsor: '#F59E0B',
    domain: '#EC4899',
    vendor: '#6366F1',
  };
  return colors[type.toLowerCase()] || '#6B7280';
}

// =========================
// Component
// =========================

export default function TopologySummary({
  data,
  onEntityClick,
  onClusterClick,
}: TopologySummaryProps) {
  const {
    metadata,
    executive_summary,
    network_metrics,
    key_actors,
    funding_flows,
    relationship_clusters,
    temporal_changes,
    methodology,
    limitations,
  } = data;

  const [activeTab, setActiveTab] = useState<'actors' | 'funding' | 'clusters' | 'temporal'>('actors');

  // Calculate max values for scaling
  const maxCentrality = useMemo(() => {
    return Math.max(...key_actors.map((a) => a.centrality_score), 0.01);
  }, [key_actors]);

  const maxFundingAmount = useMemo(() => {
    return Math.max(...funding_flows.map((f) => f.total_amount || 0), 1);
  }, [funding_flows]);

  return (
    <div className="topology-summary-report">
      {/* Report Header */}
      <header className="report-header">
        <h1>{metadata.title}</h1>
        {metadata.subtitle && <p className="subtitle">{metadata.subtitle}</p>}
        <div className="header-meta">
          <span>Generated by {metadata.generated_by}</span>
          <span>{new Date(metadata.generated_at).toLocaleString()}</span>
        </div>
      </header>

      {/* Network Metrics Overview */}
      <section className="metrics-overview">
        <h2>Network Overview</h2>
        <div className="metrics-grid">
          <MetricCard
            label="Nodes"
            value={formatNumber(network_metrics.total_nodes)}
            description="Entities in network"
          />
          <MetricCard
            label="Edges"
            value={formatNumber(network_metrics.total_edges)}
            description="Relationships mapped"
          />
          <MetricCard
            label="Density"
            value={formatPercent(network_metrics.density)}
            description="Network connectivity"
          />
          <MetricCard
            label="Avg Degree"
            value={network_metrics.average_degree.toFixed(1)}
            description="Connections per entity"
          />
          <MetricCard
            label="Clustering"
            value={formatPercent(network_metrics.clustering_coefficient)}
            description="Local clustering"
          />
          <MetricCard
            label="Centralization"
            value={formatPercent(network_metrics.centralization)}
            description="Power concentration"
          />
        </div>
      </section>

      {/* Executive Summary */}
      <section className="report-section executive-summary">
        <h2>Executive Summary</h2>
        <p>{executive_summary}</p>
      </section>

      {/* Tabbed Content */}
      <section className="tabbed-content">
        <div className="tab-nav">
          <button
            type="button"
            className={`tab-btn ${activeTab === 'actors' ? 'active' : ''}`}
            onClick={() => setActiveTab('actors')}
          >
            Key Actors ({key_actors.length})
          </button>
          <button
            type="button"
            className={`tab-btn ${activeTab === 'funding' ? 'active' : ''}`}
            onClick={() => setActiveTab('funding')}
          >
            Funding Flows ({funding_flows.length})
          </button>
          <button
            type="button"
            className={`tab-btn ${activeTab === 'clusters' ? 'active' : ''}`}
            onClick={() => setActiveTab('clusters')}
          >
            Clusters ({relationship_clusters.length})
          </button>
          {temporal_changes && temporal_changes.length > 0 && (
            <button
              type="button"
              className={`tab-btn ${activeTab === 'temporal' ? 'active' : ''}`}
              onClick={() => setActiveTab('temporal')}
            >
              Temporal Changes
            </button>
          )}
        </div>

        <div className="tab-content">
          {activeTab === 'actors' && (
            <div className="actors-tab">
              <p className="tab-description">
                Key actors ranked by network centrality - their influence on information
                and resource flows within the network.
              </p>
              <div className="actors-list">
                {key_actors.map((actor, idx) => (
                  <div
                    key={actor.id}
                    className="actor-card"
                    onClick={() => onEntityClick?.(actor)}
                    onKeyDown={(e) => e.key === 'Enter' && onEntityClick?.(actor)}
                    role="button"
                    tabIndex={0}
                  >
                    <div className="actor-rank">{idx + 1}</div>
                    <div className="actor-info">
                      <div className="actor-header">
                        <span className="actor-name">{actor.name}</span>
                        <span
                          className="actor-type"
                          style={{ backgroundColor: getEntityTypeColor(actor.entity_type) }}
                        >
                          {actor.entity_type}
                        </span>
                      </div>
                      <p className="actor-description">{actor.role_description}</p>
                      <div className="actor-metrics">
                        <span>Centrality: {formatPercent(actor.centrality_score)}</span>
                        <span>Degree: {actor.degree}</span>
                        <span>Betweenness: {actor.betweenness.toFixed(3)}</span>
                        <span>Connections: {actor.connected_entities}</span>
                      </div>
                    </div>
                    <div className="centrality-bar">
                      <div
                        className="centrality-fill"
                        style={{ height: `${(actor.centrality_score / maxCentrality) * 100}%` }}
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'funding' && (
            <div className="funding-tab">
              <p className="tab-description">
                Documented funding flows between entities, ordered by amount where available.
              </p>
              <div className="funding-list">
                {funding_flows.map((flow) => (
                  <div key={flow.id} className="funding-card">
                    <div className="flow-entities">
                      <button
                        type="button"
                        className="flow-entity source"
                        onClick={() => onEntityClick?.(flow.source)}
                      >
                        <span className="entity-name">{flow.source.name}</span>
                        <span
                          className="entity-type"
                          style={{ backgroundColor: getEntityTypeColor(flow.source.entity_type) }}
                        >
                          {flow.source.entity_type}
                        </span>
                      </button>
                      <div className="flow-arrow">
                        <span className="arrow">→</span>
                        {flow.total_amount && (
                          <span className="flow-amount">
                            {formatCurrency(flow.total_amount, flow.currency)}
                          </span>
                        )}
                      </div>
                      <button
                        type="button"
                        className="flow-entity target"
                        onClick={() => onEntityClick?.(flow.target)}
                      >
                        <span className="entity-name">{flow.target.name}</span>
                        <span
                          className="entity-type"
                          style={{ backgroundColor: getEntityTypeColor(flow.target.entity_type) }}
                        >
                          {flow.target.entity_type}
                        </span>
                      </button>
                    </div>
                    <div className="flow-meta">
                      {flow.period && (
                        <span className="flow-period">
                          {new Date(flow.period.start).getFullYear()} -{' '}
                          {new Date(flow.period.end).getFullYear()}
                        </span>
                      )}
                      <span className="evidence-count">
                        {flow.evidence_count} evidence source{flow.evidence_count !== 1 ? 's' : ''}
                      </span>
                    </div>
                    {flow.total_amount && (
                      <div className="amount-bar">
                        <div
                          className="amount-fill"
                          style={{ width: `${(flow.total_amount / maxFundingAmount) * 100}%` }}
                        />
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'clusters' && (
            <div className="clusters-tab">
              <p className="tab-description">
                Identified relationship clusters - groups of entities with higher internal
                connectivity than connections to the broader network.
              </p>
              <div className="clusters-list">
                {relationship_clusters.map((cluster) => (
                  <div
                    key={cluster.id}
                    className="cluster-card"
                    onClick={() => onClusterClick?.(cluster)}
                    onKeyDown={(e) => e.key === 'Enter' && onClusterClick?.(cluster)}
                    role="button"
                    tabIndex={0}
                  >
                    <div className="cluster-header">
                      <h3>{cluster.name}</h3>
                      <span className="cluster-size">{cluster.member_count} members</span>
                    </div>
                    <p className="cluster-description">{cluster.description}</p>
                    <div className="cluster-meta">
                      <span>Density: {formatPercent(cluster.internal_density)}</span>
                      <span>Type: {cluster.dominant_relationship_type}</span>
                    </div>
                    <div className="cluster-members">
                      <span className="members-label">Key members:</span>
                      <div className="member-chips">
                        {cluster.key_members.slice(0, 5).map((member) => (
                          <button
                            key={member.id}
                            type="button"
                            className="member-chip"
                            onClick={(e) => {
                              e.stopPropagation();
                              onEntityClick?.(member);
                            }}
                          >
                            {member.name}
                          </button>
                        ))}
                        {cluster.key_members.length > 5 && (
                          <span className="more-members">
                            +{cluster.key_members.length - 5} more
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {activeTab === 'temporal' && temporal_changes && (
            <div className="temporal-tab">
              <p className="tab-description">
                Network evolution over time showing structural changes.
              </p>
              <div className="temporal-table">
                <table>
                  <thead>
                    <tr>
                      <th>Period</th>
                      <th>Nodes +/-</th>
                      <th>Edges +/-</th>
                      <th>Density Δ</th>
                    </tr>
                  </thead>
                  <tbody>
                    {temporal_changes.map((change, idx) => (
                      <tr key={idx}>
                        <td>{change.period}</td>
                        <td>
                          <span className="change-positive">+{change.nodes_added}</span>
                          {' / '}
                          <span className="change-negative">-{change.nodes_removed}</span>
                        </td>
                        <td>
                          <span className="change-positive">+{change.edges_added}</span>
                          {' / '}
                          <span className="change-negative">-{change.edges_removed}</span>
                        </td>
                        <td>
                          <span className={change.density_change >= 0 ? 'change-positive' : 'change-negative'}>
                            {change.density_change >= 0 ? '+' : ''}{formatPercent(change.density_change)}
                          </span>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* Methodology */}
      <section className="report-section methodology">
        <h2>Methodology</h2>
        <p>{methodology}</p>
      </section>

      {/* Limitations */}
      {limitations.length > 0 && (
        <section className="report-section limitations">
          <h2>Limitations</h2>
          <ul>
            {limitations.map((limitation, idx) => (
              <li key={idx}>{limitation}</li>
            ))}
          </ul>
        </section>
      )}

      <style>{`
        .topology-summary-report {
          max-width: 900px;
          margin: 0 auto;
          font-size: 0.9375rem;
          line-height: 1.6;
        }

        .report-header {
          margin-bottom: var(--spacing-xl);
          padding-bottom: var(--spacing-lg);
          border-bottom: 2px solid var(--border-color);
        }

        .report-header h1 {
          margin-bottom: var(--spacing-xs);
          font-size: 1.75rem;
        }

        .report-header .subtitle {
          font-size: 1.125rem;
          color: var(--text-secondary);
          margin-bottom: var(--spacing-md);
        }

        .header-meta {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-md);
          font-size: 0.875rem;
          color: var(--text-muted);
        }

        .metrics-overview {
          margin-bottom: var(--spacing-xl);
        }

        .metrics-overview h2 {
          margin-bottom: var(--spacing-md);
        }

        .metrics-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(140px, 1fr));
          gap: var(--spacing-md);
        }

        .report-section {
          margin-bottom: var(--spacing-xl);
        }

        .report-section h2 {
          margin-bottom: var(--spacing-md);
          padding-bottom: var(--spacing-xs);
          border-bottom: 1px solid var(--border-color);
          font-size: 1.25rem;
        }

        .tabbed-content {
          margin-bottom: var(--spacing-xl);
        }

        .tab-nav {
          display: flex;
          gap: var(--spacing-xs);
          border-bottom: 1px solid var(--border-color);
          margin-bottom: var(--spacing-lg);
        }

        .tab-btn {
          padding: var(--spacing-sm) var(--spacing-md);
          background: none;
          border: none;
          border-bottom: 2px solid transparent;
          cursor: pointer;
          font-size: 0.875rem;
          color: var(--text-secondary);
          transition: all 0.15s ease;
        }

        .tab-btn:hover {
          color: var(--text-primary);
        }

        .tab-btn.active {
          color: var(--color-primary);
          border-bottom-color: var(--color-primary);
        }

        .tab-content {
          min-height: 300px;
        }

        .tab-description {
          color: var(--text-muted);
          margin-bottom: var(--spacing-md);
        }

        /* Actors Tab */
        .actors-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-sm);
        }

        .actor-card {
          display: grid;
          grid-template-columns: 40px 1fr 20px;
          gap: var(--spacing-md);
          padding: var(--spacing-md);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
          cursor: pointer;
          transition: background 0.15s ease;
        }

        .actor-card:hover {
          background: var(--bg-tertiary);
        }

        .actor-rank {
          font-size: 1.5rem;
          font-weight: 700;
          color: var(--text-muted);
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .actor-header {
          display: flex;
          align-items: center;
          gap: var(--spacing-sm);
          margin-bottom: var(--spacing-xs);
        }

        .actor-name {
          font-weight: 600;
        }

        .actor-type {
          padding: 2px 6px;
          border-radius: 4px;
          color: white;
          font-size: 0.625rem;
          text-transform: uppercase;
        }

        .actor-description {
          font-size: 0.875rem;
          color: var(--text-secondary);
          margin-bottom: var(--spacing-xs);
        }

        .actor-metrics {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-md);
          font-size: 0.75rem;
          color: var(--text-muted);
        }

        .centrality-bar {
          width: 8px;
          background: var(--bg-tertiary);
          border-radius: 4px;
          display: flex;
          flex-direction: column;
          justify-content: flex-end;
        }

        .centrality-fill {
          background: var(--color-primary);
          border-radius: 4px;
          min-height: 4px;
        }

        /* Funding Tab */
        .funding-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-md);
        }

        .funding-card {
          padding: var(--spacing-md);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
        }

        .flow-entities {
          display: flex;
          align-items: center;
          gap: var(--spacing-sm);
          margin-bottom: var(--spacing-sm);
        }

        .flow-entity {
          flex: 1;
          display: flex;
          flex-direction: column;
          align-items: flex-start;
          padding: var(--spacing-sm);
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
          border-radius: var(--border-radius);
          cursor: pointer;
        }

        .flow-entity:hover {
          border-color: var(--color-primary);
        }

        .flow-entity .entity-name {
          font-weight: 500;
          margin-bottom: 2px;
        }

        .flow-entity .entity-type {
          padding: 2px 6px;
          border-radius: 4px;
          color: white;
          font-size: 0.625rem;
          text-transform: uppercase;
        }

        .flow-arrow {
          display: flex;
          flex-direction: column;
          align-items: center;
          gap: 2px;
          padding: 0 var(--spacing-sm);
        }

        .flow-arrow .arrow {
          font-size: 1.5rem;
          color: var(--text-muted);
        }

        .flow-amount {
          font-size: 0.75rem;
          font-weight: 600;
          color: var(--color-success);
        }

        .flow-meta {
          display: flex;
          gap: var(--spacing-md);
          font-size: 0.75rem;
          color: var(--text-muted);
          margin-bottom: var(--spacing-sm);
        }

        .amount-bar {
          height: 4px;
          background: var(--bg-tertiary);
          border-radius: 2px;
        }

        .amount-fill {
          height: 100%;
          background: var(--color-success);
          border-radius: 2px;
        }

        /* Clusters Tab */
        .clusters-list {
          display: flex;
          flex-direction: column;
          gap: var(--spacing-md);
        }

        .cluster-card {
          padding: var(--spacing-md);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
          cursor: pointer;
          transition: background 0.15s ease;
        }

        .cluster-card:hover {
          background: var(--bg-tertiary);
        }

        .cluster-header {
          display: flex;
          justify-content: space-between;
          align-items: center;
          margin-bottom: var(--spacing-xs);
        }

        .cluster-header h3 {
          margin: 0;
          font-size: 1rem;
        }

        .cluster-size {
          font-size: 0.75rem;
          color: var(--text-muted);
          background: var(--bg-tertiary);
          padding: 2px 8px;
          border-radius: 4px;
        }

        .cluster-description {
          font-size: 0.875rem;
          color: var(--text-secondary);
          margin-bottom: var(--spacing-sm);
        }

        .cluster-meta {
          display: flex;
          gap: var(--spacing-md);
          font-size: 0.75rem;
          color: var(--text-muted);
          margin-bottom: var(--spacing-sm);
        }

        .cluster-members {
          padding-top: var(--spacing-sm);
          border-top: 1px solid var(--border-color);
        }

        .members-label {
          font-size: 0.75rem;
          color: var(--text-muted);
          display: block;
          margin-bottom: var(--spacing-xs);
        }

        .member-chips {
          display: flex;
          flex-wrap: wrap;
          gap: var(--spacing-xs);
        }

        .member-chip {
          padding: 2px 8px;
          background: var(--bg-primary);
          border: 1px solid var(--border-color);
          border-radius: var(--border-radius);
          font-size: 0.75rem;
          cursor: pointer;
        }

        .member-chip:hover {
          border-color: var(--color-primary);
        }

        .more-members {
          font-size: 0.75rem;
          color: var(--text-muted);
          padding: 2px 8px;
        }

        /* Temporal Tab */
        .temporal-table {
          overflow-x: auto;
        }

        .temporal-table table {
          width: 100%;
          border-collapse: collapse;
        }

        .temporal-table th,
        .temporal-table td {
          padding: var(--spacing-sm);
          text-align: left;
          border-bottom: 1px solid var(--border-color);
        }

        .temporal-table th {
          font-weight: 600;
          font-size: 0.75rem;
          text-transform: uppercase;
          color: var(--text-muted);
        }

        .change-positive {
          color: var(--color-success);
        }

        .change-negative {
          color: var(--color-danger);
        }

        .limitations ul {
          margin: 0;
          padding-left: var(--spacing-lg);
        }

        .limitations li {
          margin-bottom: var(--spacing-xs);
          color: var(--text-secondary);
        }

        @media (max-width: 768px) {
          .metrics-grid {
            grid-template-columns: repeat(2, 1fr);
          }

          .tab-nav {
            overflow-x: auto;
          }

          .flow-entities {
            flex-direction: column;
          }

          .flow-entity {
            width: 100%;
          }

          .flow-arrow {
            transform: rotate(90deg);
            padding: var(--spacing-xs) 0;
          }
        }
      `}</style>
    </div>
  );
}

// =========================
// Metric Card Component
// =========================

interface MetricCardProps {
  label: string;
  value: string;
  description: string;
}

function MetricCard({ label, value, description }: MetricCardProps) {
  return (
    <div className="metric-card">
      <div className="metric-value">{value}</div>
      <div className="metric-label">{label}</div>
      <div className="metric-description">{description}</div>

      <style>{`
        .metric-card {
          padding: var(--spacing-md);
          background: var(--bg-secondary);
          border-radius: var(--border-radius);
          text-align: center;
        }

        .metric-card .metric-value {
          font-size: 1.75rem;
          font-weight: 700;
          color: var(--color-primary);
        }

        .metric-card .metric-label {
          font-size: 0.875rem;
          font-weight: 500;
          margin-bottom: 2px;
        }

        .metric-card .metric-description {
          font-size: 0.75rem;
          color: var(--text-muted);
        }
      `}</style>
    </div>
  );
}
